%%{ init : { "theme": "neutral" } }%%

sequenceDiagram
title FETCHING A LIST OF PLACES
actor User
participant API
participant BusinessLogic
participant Database@{ "type" : "database" }

User->>API: ListPlace
API->>BusinessLogic: CheckRequest

alt Validation Failed
    BusinessLogic-->>API: Return Failure
    API-->>User: ShowResult
else Validation success
    BusinessLogic->>Database: ReadList
    Database-->>BusinessLogic: ReturnList
    BusinessLogic-->>API: ReturnList
    API-->>User: ShowResult
end

Note left of User: The User wants to list all the places with certains attributes:<br/>- Title<br/>- Exact price or between two prices<br/>- Latitude<br/>- longitude

Note over API: The API will check the request send by the user and call the rights methods.

Note over BusinessLogic: This layer will check if the request can enter the database:<br/>- If the coordinates given by the user can be reachable

Note right of Database: Will Read inside of the Database every places that match the user contraints and will return a list of them for the user to see.