classDiagram

class PresentationLayer {
    user_request()
    show_result()
}

class user_facade {
    add_user()
    update_user()
    delete_user()
}
class place_facade{
    create_place()
    update_place()
    delete_place()
    list_place()
}
class review_facade{
    add_review()
    update_review()
    delete_review()
    list_review()
}
class amenity_facade{
    add_amenity()
    update_amenity()
    delete_amenity()
    list_amenity()
}

class BusinessLogicLayer {
    check_request()
    validate_request()
}

class PersistenceLayer {
    read()
    write()
    update()
    delete()
}

PresentationLayer --> user_facade
PresentationLayer --> place_facade
PresentationLayer --> amenity_facade
PresentationLayer --> review_facade
user_facade --> BusinessLogicLayer
place_facade --> BusinessLogicLayer
amenity_facade --> BusinessLogicLayer
review_facade --> BusinessLogicLayer
BusinessLogicLayer --> PersistenceLayer : Database operations

note for PresentationLayer "This layer handles communication with the user:
It's the interface of the application."

note for BusinessLogicLayer "This layer is the core logic of the application:
    It checks if a request can access to the database
    and determines what actions should be taken."

note for PersistenceLayer "This layer interact directly with the database:
    After the request is confirmed, it will perform the necessary operations
    to read, write or update the database."

note for user_facade "The facades is used to order the application:
It call the right methods depending of the user request"