classDiagram

class PresentationLayer {
    UserRequest()
    ShowResult()
}

class UserFacade {
    AddUser()
    UpdateUser()
    DeleteUser()
}
class PlaceFacade{
    CreatePlace()
    UpdatePlace()
    DeletePlace()
    ListPlace()
}
class ReviewFacade{
    AddReview()
    UpdateReview()
    DeleteReview()
    ListReview()
}
class AmenityFacade{
    AddAmenity()
    UpdateAmenity()
    DeleteAmenity()
    ListAmenity()
}

class BusinessLogicLayer {
    CheckRequest()
    ValidateRequest()
}

class PersistenceLayer {
    Read()
    Write()
    Update()
    Delete()
}

PresentationLayer --> UserFacade
PresentationLayer --> PlaceFacade
PresentationLayer --> AmenityFacade
PresentationLayer --> ReviewFacade
UserFacade --> BusinessLogicLayer
PlaceFacade --> BusinessLogicLayer
AmenityFacade --> BusinessLogicLayer
ReviewFacade --> BusinessLogicLayer
BusinessLogicLayer --> PersistenceLayer : Database operations

note for PresentationLayer "This layer handles communication with the user:
It's the interface of the application."

note for BusinessLogicLayer "This layer is the core logic of the application:
    It checks if a request can access to the database
    and determines what actions should be taken."

note for PersistenceLayer "This layer interact directly with the database:
    After the request is confirmed, it will perform the necessary operations
    to read, write or update the database."

note for UserFacade "The facades is used to order the application:
It call the right methods depending of the user request"