%%{ init : { "theme": "neutral" } }%%

sequenceDiagram
participant User
participant API
participant BusinessLogic
participant Database

User->>API: add_user()
API->>BusinessLogic: check_request()


alt Validation failed
    BusinessLogic-->>API: Return Failure
    API-->>User:show_result()
else Validation success
    BusinessLogic->>Database: AddUser
    Database-->>BusinessLogic: UserCreated
    BusinessLogic-->>API: Return Response
    API-->>User: show_result()
end