%%{ init : { "theme": "neutral" } }%%

sequenceDiagram
title USER REGISTRATION
participant User
participant API
participant BusinessLogic
participant Database

User->>API: AddUser
API->>BusinessLogic: CheckRequest

alt Validation Failed
    BusinessLogic-->>API: Return Failure
    API-->>User: ShowResult
else Validation success
    BusinessLogic->>Database: AddUser
    Database-->>BusinessLogic: UserCreated
    BusinessLogic-->>API: Return Response
    API-->>User: ShowResult
end